(* This file is generated by ortac qcheck-stm,
   edit how you run the tool instead *)
[@@@ocaml.warning "-26-27-69-32-34-38"]
open Treiber_stack
module Ortac_runtime = Ortac_runtime_qcheck_stm_domain
let seq_is_empty s =
  try s = Ortac_runtime.Gospelstdlib.Sequence.empty
  with
  | e ->
      raise
        (Ortac_runtime.Partial_function
           (e,
             {
               Ortac_runtime.start =
                 {
                   pos_fname = "treiber_stack.mli";
                   pos_lnum = 9;
                   pos_bol = 291;
                   pos_cnum = 298
                 };
               Ortac_runtime.stop =
                 {
                   pos_fname = "treiber_stack.mli";
                   pos_lnum = 9;
                   pos_bol = 291;
                   pos_cnum = 316
                 }
             }))
module SUT =
  (Ortac_runtime.SUT.Make)(struct type sut = int t
                                  let init () = create () end)
module ModelElt =
  struct
    type nonrec elt = {
      contents: int Ortac_runtime.Gospelstdlib.sequence }
    let init =
      let () = () in
      {
        contents =
          (try Ortac_runtime.Gospelstdlib.Sequence.empty
           with
           | e ->
               raise
                 (Ortac_runtime.Partial_function
                    (e,
                      {
                        Ortac_runtime.start =
                          {
                            pos_fname = "treiber_stack.mli";
                            pos_lnum = 18;
                            pos_bol = 996;
                            pos_cnum = 1021
                          };
                        Ortac_runtime.stop =
                          {
                            pos_fname = "treiber_stack.mli";
                            pos_lnum = 18;
                            pos_bol = 996;
                            pos_cnum = 1035
                          }
                      })))
      }
  end
module Model = (Ortac_runtime.Model.Make)(ModelElt)
module Spec =
  struct
    open STM
    module QCheck =
      struct
        include QCheck
        module Gen = struct include Gen
                            let int = nat
                            let list = small_list end
      end
    type _ ty +=  
      | Integer: Ortac_runtime.integer ty 
    let integer = (Integer, Ortac_runtime.string_of_integer)
    type _ ty +=  
      | SUT: SUT.elt ty 
    let sut = (SUT, (fun _ -> "<sut>"))
    type sut = SUT.t
    let init_sut = SUT.create 1
    type state = Model.t
    let init_state = Model.create 1 ()
    type cmd_ =
      | Create of unit 
      | Is_empty 
      | Peek_opt 
      | Pop_opt 
      | Pop_all 
      | Push of int 
      | Push_all of int list 
    type cmd = (bool * cmd_)
    let show_cmd (_, cmd__001_) =
      match cmd__001_ with
      | Create () ->
          Format.asprintf "%s %a" "create" (Util.Pp.pp_unit true) ()
      | Is_empty -> Format.asprintf "%s <sut>" "is_empty"
      | Peek_opt -> Format.asprintf "%s <sut>" "peek_opt"
      | Pop_opt -> Format.asprintf "%s <sut>" "pop_opt"
      | Pop_all -> Format.asprintf "%s <sut>" "pop_all"
      | Push x ->
          Format.asprintf "%s <sut> %a" "push" (Util.Pp.pp_int true) x
      | Push_all xs ->
          Format.asprintf "%s <sut> %a" "push_all"
            (Util.Pp.pp_list Util.Pp.pp_int true) xs
    let cleanup _ = ()
    let arb_cmd_flag flag _ =
      let open QCheck in
        make ~print:show_cmd
          (let open Gen in
          pair (return flag) @@
             oneof
               [(pure (fun () -> Create ())) <*> unit;
               pure Is_empty;
               pure Peek_opt;
               pure Pop_opt;
               pure Pop_all;
               (pure (fun x -> Push x)) <*> int;
               (pure (fun xs -> Push_all xs)) <*> (list int)])
    let arb_cmd = arb_cmd_flag false
    let arb_cmd = arb_cmd_flag true
    let next_state (flag, cmd__002_) state__003_ =
      match cmd__002_ with
      | Create () ->
          let a_1__005_ =
            let open ModelElt in
              {
                contents =
                  (try Ortac_runtime.Gospelstdlib.Sequence.empty
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "treiber_stack.mli";
                                    pos_lnum = 18;
                                    pos_bol = 996;
                                    pos_cnum = 1021
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "treiber_stack.mli";
                                    pos_lnum = 18;
                                    pos_bol = 996;
                                    pos_cnum = 1035
                                  }
                              })))
              } in
          if flag
          then Model.push (Model.drop_n state__003_ 0) a_1__005_
          else Model.drop_n state__003_ 0
      | Is_empty ->
          let a_2__006_ = Model.get state__003_ 0 in
          let a_2__007_ = a_2__006_ in
          Model.push (Model.drop_n state__003_ 1) a_2__007_
      | Peek_opt ->
          let a_3__008_ = Model.get state__003_ 0 in
          let a_3__009_ = a_3__008_ in
          Model.push (Model.drop_n state__003_ 1) a_3__009_
      | Pop_opt ->
          let a_4__010_ = Model.get state__003_ 0 in
          let a_4__011_ =
            let open ModelElt in
              {
                contents =
                  (try
                     if seq_is_empty a_4__010_.contents
                     then Ortac_runtime.Gospelstdlib.Sequence.empty
                     else
                       Ortac_runtime.Gospelstdlib.Sequence.tl
                         a_4__010_.contents
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "treiber_stack.mli";
                                    pos_lnum = 58;
                                    pos_bol = 2863;
                                    pos_cnum = 2888
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "treiber_stack.mli";
                                    pos_lnum = 60;
                                    pos_bol = 2966;
                                    pos_cnum = 3024
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__003_ 1) a_4__011_
      | Pop_all ->
          let a_5__012_ = Model.get state__003_ 0 in
          let a_5__013_ =
            let open ModelElt in
              {
                contents =
                  (try Ortac_runtime.Gospelstdlib.Sequence.empty
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "treiber_stack.mli";
                                    pos_lnum = 89;
                                    pos_bol = 3918;
                                    pos_cnum = 3943
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "treiber_stack.mli";
                                    pos_lnum = 89;
                                    pos_bol = 3918;
                                    pos_cnum = 3957
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__003_ 1) a_5__013_
      | Push x ->
          let a_6__014_ = Model.get state__003_ 0 in
          let a_6__015_ =
            let open ModelElt in
              {
                contents =
                  (try
                     Ortac_runtime.Gospelstdlib.Sequence.cons x
                       a_6__014_.contents
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "treiber_stack.mli";
                                    pos_lnum = 98;
                                    pos_bol = 4418;
                                    pos_cnum = 4443
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "treiber_stack.mli";
                                    pos_lnum = 98;
                                    pos_bol = 4418;
                                    pos_cnum = 4475
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__003_ 1) a_6__015_
      | Push_all xs ->
          let a_7__016_ = Model.get state__003_ 0 in
          let a_7__017_ =
            let open ModelElt in
              {
                contents =
                  (try
                     Ortac_runtime.Gospelstdlib.(++)
                       (Ortac_runtime.Gospelstdlib.Sequence.rev
                          (Ortac_runtime.Gospelstdlib.List.to_seq xs))
                       a_7__016_.contents
                   with
                   | e ->
                       raise
                         (Ortac_runtime.Partial_function
                            (e,
                              {
                                Ortac_runtime.start =
                                  {
                                    pos_fname = "treiber_stack.mli";
                                    pos_lnum = 119;
                                    pos_bol = 5180;
                                    pos_cnum = 5235
                                  };
                                Ortac_runtime.stop =
                                  {
                                    pos_fname = "treiber_stack.mli";
                                    pos_lnum = 119;
                                    pos_bol = 5180;
                                    pos_cnum = 5237
                                  }
                              })))
              } in
          Model.push (Model.drop_n state__003_ 1) a_7__017_
    let precond (_, cmd__044_) state__045_ =
      match cmd__044_ with
      | Create () -> true
      | Is_empty -> true
      | Peek_opt -> true
      | Pop_opt -> true
      | Pop_all -> true
      | Push x -> true
      | Push_all xs -> true
    let postcond _ _ _ = true
    let run (flag, cmd__046_) sut__047_ =
      match cmd__046_ with
      | Create () ->
          Res
            (sut,
              (let res__048_ = create () in
              (if flag
               then (SUT.push sut__047_ res__048_; res__048_ )
               else res__048_)))
      | Is_empty ->
          Res
            (bool,
              (let a_2__049_ = SUT.get sut__047_ 0 in
               let res__050_ = is_empty a_2__049_ in res__050_))
      | Peek_opt ->
          Res
            ((option int),
              (let a_3__051_ = SUT.get sut__047_ 0 in
               let res__052_ = peek_opt a_3__051_ in res__052_))
      | Pop_opt ->
          Res
            ((option int),
              (let a_4__053_ = SUT.get sut__047_ 0 in
               let res__054_ = pop_opt a_4__053_ in res__054_))
      | Pop_all ->
          Res
            ((list int),
              (let a_5__055_ = SUT.get sut__047_ 0 in
               let res__056_ = pop_all a_5__055_ in res__056_))
      | Push x ->
          Res
            (unit,
              (let a_6__057_ = SUT.get sut__047_ 0 in
               let res__058_ = push a_6__057_ x in res__058_))
      | Push_all xs ->
          Res
            (unit,
              (let a_7__059_ = SUT.get sut__047_ 0 in
               let res__060_ = push_all a_7__059_ xs in res__060_))
  end
module STMTests = (Ortac_runtime.Make)(Spec)
let check_init_state () = ()
let ortac_show_cmd (_, cmd__062_) state__063_ last__065_ res__064_ =
  let open Spec in
    let open STM in
      match (cmd__062_, res__064_) with
      | (Create (), Res ((SUT, _), a_1)) ->
          let lhs = if last__065_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %a" lhs "create"
            (Util.Pp.pp_unit true) ()
      | (Is_empty, Res ((Bool, _), _)) ->
          let lhs = if last__065_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s" lhs "is_empty"
            (SUT.get_name state__063_ (0 + shift))
      | (Peek_opt, Res ((Option (Int), _), _)) ->
          let lhs = if last__065_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s" lhs "peek_opt"
            (SUT.get_name state__063_ (0 + shift))
      | (Pop_opt, Res ((Option (Int), _), _)) ->
          let lhs = if last__065_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s" lhs "pop_opt"
            (SUT.get_name state__063_ (0 + shift))
      | (Pop_all, Res ((List (Int), _), _)) ->
          let lhs = if last__065_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s" lhs "pop_all"
            (SUT.get_name state__063_ (0 + shift))
      | (Push x, Res ((Unit, _), _)) ->
          let lhs = if last__065_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s %a" lhs "push"
            (SUT.get_name state__063_ (0 + shift)) (Util.Pp.pp_int true) x
      | (Push_all xs, Res ((Unit, _), _)) ->
          let lhs = if last__065_ then "r" else "_"
          and shift = 0 in
          Format.asprintf "let %s = %s %s %a" lhs "push_all"
            (SUT.get_name state__063_ (0 + shift))
            (Util.Pp.pp_list Util.Pp.pp_int true) xs
      | _ -> assert false
let ortac_postcond (flag, cmd__018_) state__019_ res__020_ =
  let open Spec in
    let open STM in
      let new_state__021_ = lazy (next_state (flag, cmd__018_) state__019_) in
      match (cmd__018_, res__020_) with
      | (Create (), Res ((SUT, _), a_1)) -> None
      | (Is_empty, Res ((Bool, _), b)) ->
          if
            let a_old__024_ = Model.get state__019_ 0
            and a_new__025_ = lazy (Model.get (Lazy.force new_state__021_) 0) in
            (try
               (b = true) = (seq_is_empty (Lazy.force a_new__025_).contents)
             with | e -> false)
          then None
          else
            Some
              (Ortac_runtime.Report.report "Treiber_stack" "create ()"
                 (try
                    Ortac_runtime.Report.Value
                      (Res
                         (bool,
                           (let a_old__022_ = Model.get state__019_ 0
                            and a_new__023_ =
                              lazy (Model.get (Lazy.force new_state__021_) 0) in
                            seq_is_empty (Lazy.force a_new__023_).contents)))
                  with | e -> Ortac_runtime.Report.Out_of_domain) "is_empty"
                 [("b = seq_is_empty a.contents",
                    {
                      Ortac_runtime.start =
                        {
                          pos_fname = "treiber_stack.mli";
                          pos_lnum = 27;
                          pos_bol = 1433;
                          pos_cnum = 1445
                        };
                      Ortac_runtime.stop =
                        {
                          pos_fname = "treiber_stack.mli";
                          pos_lnum = 27;
                          pos_bol = 1433;
                          pos_cnum = 1472
                        }
                    })])
      | (Peek_opt, Res ((Option (Int), _), o)) ->
          if
            let a_old__029_ = Model.get state__019_ 0
            and a_new__030_ = lazy (Model.get (Lazy.force new_state__021_) 0) in
            (try
               o =
                 (if seq_is_empty (Lazy.force a_new__030_).contents
                  then None
                  else
                    Some
                      (Ortac_runtime.Gospelstdlib.Sequence.hd
                         (Lazy.force a_new__030_).contents))
             with | e -> false)
          then None
          else
            Some
              (Ortac_runtime.Report.report "Treiber_stack" "create ()"
                 (try
                    Ortac_runtime.Report.Value
                      (Res
                         ((option int),
                           (let a_old__027_ = Model.get state__019_ 0
                            and a_new__028_ =
                              lazy (Model.get (Lazy.force new_state__021_) 0) in
                            if seq_is_empty (Lazy.force a_new__028_).contents
                            then None
                            else
                              Some
                                (Ortac_runtime.Gospelstdlib.Sequence.hd
                                   (Lazy.force a_new__028_).contents))))
                  with | e -> Ortac_runtime.Report.Out_of_domain) "peek_opt"
                 [("o = if seq_is_empty a.contents\n                then None\n                else Some (Sequence.hd a.contents)",
                    {
                      Ortac_runtime.start =
                        {
                          pos_fname = "treiber_stack.mli";
                          pos_lnum = 44;
                          pos_bol = 2178;
                          pos_cnum = 2190
                        };
                      Ortac_runtime.stop =
                        {
                          pos_fname = "treiber_stack.mli";
                          pos_lnum = 46;
                          pos_bol = 2247;
                          pos_cnum = 2297
                        }
                    })])
      | (Pop_opt, Res ((Option (Int), _), o_1)) ->
          if
            let a_old__034_ = Model.get state__019_ 0
            and a_new__035_ = lazy (Model.get (Lazy.force new_state__021_) 0) in
            (try
               o_1 =
                 (if seq_is_empty a_old__034_.contents
                  then None
                  else
                    Some
                      (Ortac_runtime.Gospelstdlib.Sequence.hd
                         a_old__034_.contents))
             with | e -> false)
          then None
          else
            Some
              (Ortac_runtime.Report.report "Treiber_stack" "create ()"
                 (try
                    Ortac_runtime.Report.Value
                      (Res
                         ((option int),
                           (let a_old__032_ = Model.get state__019_ 0
                            and a_new__033_ =
                              lazy (Model.get (Lazy.force new_state__021_) 0) in
                            if seq_is_empty a_old__032_.contents
                            then None
                            else
                              Some
                                (Ortac_runtime.Gospelstdlib.Sequence.hd
                                   a_old__032_.contents))))
                  with | e -> Ortac_runtime.Report.Out_of_domain) "pop_opt"
                 [("o = if seq_is_empty (old a.contents)\n                then None\n                else Some (Sequence.hd (old a.contents))",
                    {
                      Ortac_runtime.start =
                        {
                          pos_fname = "treiber_stack.mli";
                          pos_lnum = 61;
                          pos_bol = 3025;
                          pos_cnum = 3037
                        };
                      Ortac_runtime.stop =
                        {
                          pos_fname = "treiber_stack.mli";
                          pos_lnum = 63;
                          pos_bol = 3100;
                          pos_cnum = 3156
                        }
                    })])
      | (Pop_all, Res ((List (Int), _), xs_1)) ->
          if
            let a_old__039_ = Model.get state__019_ 0
            and a_new__040_ = lazy (Model.get (Lazy.force new_state__021_) 0) in
            (try
               xs_1 =
                 (Ortac_runtime.Gospelstdlib.List.of_seq a_old__039_.contents)
             with | e -> false)
          then None
          else
            Some
              (Ortac_runtime.Report.report "Treiber_stack" "create ()"
                 (try
                    Ortac_runtime.Report.Value
                      (Res
                         ((list int),
                           (let a_old__037_ = Model.get state__019_ 0
                            and a_new__038_ =
                              lazy (Model.get (Lazy.force new_state__021_) 0) in
                            Ortac_runtime.Gospelstdlib.List.of_seq
                              a_old__037_.contents)))
                  with | e -> Ortac_runtime.Report.Out_of_domain) "pop_all"
                 [("xs = List.of_seq (old a.contents)",
                    {
                      Ortac_runtime.start =
                        {
                          pos_fname = "treiber_stack.mli";
                          pos_lnum = 90;
                          pos_bol = 3958;
                          pos_cnum = 3970
                        };
                      Ortac_runtime.stop =
                        {
                          pos_fname = "treiber_stack.mli";
                          pos_lnum = 90;
                          pos_bol = 3958;
                          pos_cnum = 4003
                        }
                    })])
      | (Push x, Res ((Unit, _), _)) -> None
      | (Push_all xs, Res ((Unit, _), _)) -> None
      | _ -> None
let _ =
  QCheck_base_runner.run_tests_main
    (let count = 1000 in
     [STMTests.agree_test ~count ~name:"Treiber_stack STM tests" 1
        check_init_state ortac_show_cmd ortac_postcond])
